name: MLOps Pipeline CI/CD

on:
  push:
    branches:
      - main

jobs:
  # Job 1-> Run Tests
  test_suite:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --no-cache-dir -r requirements.txt

      - name: Run tests
        run: |
          pytest --disable-warnings -q

  # Job 2-> Train and Quantize
  train_and_quantize:
    runs-on: ubuntu-latest
    needs: test_suite
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install --no-cache-dir -r requirements.txt

      - name: Train model
        run: |
          python -m src.train

      - name: Quantize model
        run: |
          python -m src.quantize

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: model-artifacts
          path: artifacts/

  # Job 3-> Build and Test Docker Container
  build_and_test_container:
    runs-on: ubuntu-latest
    needs: train_and_quantize
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: model-artifacts
          path: artifacts/

      - name: Build Docker image
        run: |
          docker build -t mlops-pipeline .

      - name: Run container and verify prediction
        run: |
          docker run --rm mlops-pipeline
